### ISSUE TITLE
🥰🙏: Thanks for this tool

### ISSUE THREAD

**Issue by 3d-gussner** [Jnesselr/fusion-360-total-exporter#11]
Thanks you and everyone contribution so much for this Add-in.😍

**Comment by Jnesselr** [comment]
I'm glad you like it! I'm glad I can help the community out like this.

**Comment by 3d-gussner** [comment]
Keep it open so people can see it. Positive reports are rare and hopefully people will join your project.

**Comment by Jnesselr** [comment]
I do appreciate the positive report, but as a maintainer it actually makes it harder for me to maintain to have open reports. I have had some awesome pull requests so far and I do look forward to more in the future!

I did go ahead and pin this issue though, because positive experiences do make me happy!
